# This is the config file used for the tests.
# You should not use it for real.  Ideally, you
# should have a config stored as a secret somewhere
# which you mount (say to /secrets/conifg.yaml),
# and then set the env var SNPIT_CONFIG to point
# to that config.

webserver:
  flask_secret_key: o6950bi77gvbc2jie49lklotwll69ayv
  sessionstore: /sessions
  emailfrom: raknop@lbl.gov
  smtpserver: smtp.lbl.gov
  smtpport: 25
  smtpusessl: False
  smtpusername: NULL
  smtppassword: NULL
  

db:
  host: postgres
  port: 5432
  name: roman_snpit
  user: postgres
  passwd: fragile
